packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@tailwindcss/postcss': latest
  '@types/node': latest
  '@types/react': latest
  '@types/react-dom': latest
  eslint: latest
  lucide-react: latest
  next: latest
  react: latest
  react-dom: latest
  tailwind-variants: latest
  tailwindcss: latest
  tw-animate-css: latest
  typescript: latest
  zod: ^3.25.76
